#54:- delete `without` keys
RonasIT/laravel-entity-generator pull request #15
Opened 2022-07-05 07:20 UTC by pirs1337

2022-07-06 07:19 UTC, DenTray requested changes

2022-07-06 07:19 UTC, DenTray commented on src/Commands/MakeEntityCommand.php
> -    protected function getMethods()
we should keep an ability to generate only particallar classes

2022-07-08 12:45 UTC, pirs1337 commented on src/Commands/MakeEntityCommand.php
> -    protected function getMethods()
as discussed, you`ll test.

2022-07-13 05:57 UTC, DenTray commented on src/Commands/MakeEntityCommand.php
> -    protected function getMethods()
checked, works fine

2022-07-13 05:57 UTC, merged