#20: Fixed bug with non-existent dir when creating new entity, renamed stub configs, added namespace for DatabaseSeeder
RonasIT/laravel-entity-generator pull request #27
Opened 2023-03-12 08:42 UTC by vitgrams

2023-03-13 05:59 UTC, vitgrams commented
@DenTray Done. Could you please review this code?

2023-03-13 06:26 UTC, DenTray requested changes

2023-03-13 06:26 UTC, DenTray commented on src/Generators/FactoryGenerator.php
> +        $createMessage = (floatval(app()->version()) >= 8)
could we use https://www.php.net/manual/en/function.version-compare.php ?

2023-03-15 09:35 UTC, vitgrams commented
@DenTray Fixed code review remarks.

2023-03-22 02:01 UTC, DenTray requested changes

2023-03-22 02:01 UTC, DenTray commented on src/Generators/SeederGenerator.php
> +            $databaseSeederDir = implode('/', $databaseSeederPathSegments);
please use helper for it https://github.com/RonasIT/laravel-helpers/blob/master/src/helpers.php#L395

2023-03-22 13:11 UTC, vitgrams commented
@DenTray Fixed review remarks.

2023-03-28 03:40 UTC, DenTray approved these changes

2023-03-28 03:40 UTC, DenTray commented on src/Generators/SeederGenerator.php
> +            list(, $databaseSeederDir) = extract_last_part($this->databaseSeederPath, '/');
```suggestion
            list($basePath, $databaseSeederDir) = extract_last_part($this->databaseSeederPath, '/');
```

2023-03-28 03:40 UTC, merged